---
title: "Graficos: indices redundancia con vrs sin palmas effect traits"
author: "Erick Calderón-Morales"
date: "March 26, 2019"
output:   
 html_document:
   code_folding: hide
   fig_height: 8
   fig_width: 10
   keep_md: yes
   toc: yes
   toc_depth: 2
   toc_float: yes
---

```{r}
#Paquetes
library(tidyverse)
library(janitor)
```


#Objetivo
Comparar que tanto varian los indices de redundancia funcional con y sin palmas


```{r}
#Cargar datos
dfdiver_eff <- read.csv("C:/tesis_catie/Calderon_CATIE/data/resultados_csv/data_indices_eff_fdiver.csv", header = T)
dfdiver_eff <- dfdiver_eff %>% clean_names()


dfdiver_eff_sp <- read.csv("C:/tesis_catie/Calderon_CATIE/data/resultados_csv/data_indices_eff_fdiver_sp.csv", header=T)
dfdiver_eff_sp <- dfdiver_eff_sp %>% clean_names()

dparcelas <- read.csv("C:/tesis_catie/Calderon_CATIE/data/clean/data_posicion_parcelas.csv", header=T)

```



##Indices FEve, FDiv, FDis, Rasgos effecto
```{r}
#Join data

 left_join(dfdiver_eff,dfdiver_eff_sp, by="plot") %>% 
  left_join(., dparcelas, by="plot") %>% 
  
  gather("fdis","feve","fdiv","fdis_sp","feve_sp","fdiv_sp",key="indices", value ="valor") %>% 
  group_by(indices, forest_type) %>% 
  summarise(mean = 
              mean(valor)) %>% 
  arrange(forest_type) %>% 
  print(n=30)

#ggplot(data=djoin, aes(indices, mean)) + 
# geom_bar(stat = "identity") + 
# facet_grid(.~forest_type)+
#  theme(axis.text.x = element_text(angle = 90))
```

##Indices FEve, FDiv, FDis, Rasgos respuesta

```{r}
#Cargar datos
dfiver_resp <- read.csv("C:/tesis_catie/Calderon_CATIE/data/resultados_csv/data_indices_resp_fdiver.csv", header = T)
dfiver_resp <- dfiver_resp %>% clean_names()


dfiver_resp_sp <- read.csv("C:/tesis_catie/Calderon_CATIE/data/resultados_csv/data_indices_resp_fdiver_sp.csv", header=T)
dfiver_resp_sp <- dfiver_resp_sp %>%clean_names()

dparcelas <- read.csv("C:/tesis_catie/Calderon_CATIE/data/clean/data_posicion_parcelas.csv", header=T)

```


```{r}
#Join data

 left_join(dfiver_resp, dfiver_resp_sp, by="plot") %>% 
  left_join(., dparcelas, by="plot") %>% 
  
  gather("fdis","feve","fdiv","fdis_sp","feve_sp","fdiv_sp",key="indices", value ="valor") %>% 
  group_by(indices, forest_type) %>% 
  summarise(mean = 
              mean(valor)) %>% 
  arrange(forest_type) %>% 
  print(n=30)

```

